#pragma once

#include <windows.h>
#include <assert.h>
#include <stdio.h>
#include <math.h>
#include <float.h>
#include <io.h>
#include <sys/stat.h>
#include <Shlwapi.h>
#include <Shlobj.h>
#include <memory.h>

class cVec2;
class cVec3;
class cVec4;
class cMat2;
class cMat3;
class cMat4;
class cAngles;
class cQuat;
class cRotation;
class cBounds;
class cSphere;
class cPlane;
class cColor;
class cStr;
class cBitMap;
class cDIB24;
class cRawMesh;
class cIO;
class cHashIndex;
class cHelpers;

class dVector;
class dMatrix;

#pragma pack(push)
#pragma pack(1)

#include "cMath.h"
#include "cVec2.h"
#include "cVec3.h"
#include "cVec4.h"
#include "cVector.h"
#include "dVector.h"
#include "cList.h"
#include "cMat2.h"
#include "cMat3.h"
#include "cMat4.h"
#include "cMatrix.h"
#include "dMatrix.h"
#include "cVectors.h"
#include "cQuat.h"
#include "cAngles.h"
#include "cRotation.h"
#include "cList.h"
#include "cColor.h"
#include "cStr.h"
#include "cHashIndex.h"
#include "cDIB24.h"
#include "cBitMap.h"
#include "cRawMesh.h"
#include "cIO.h"
#include "cSolver.h"
#include "cTimer.h"
#include "cHelpers.h"
#include "cSphere.h"
#include "cPlane.h"
#include "cBounds.h"
#include "cSegBezier.h"
#include "cSplineBezier.h"
#include "cViewPort2.h"
#include "cExtrapolate.h"
#include "cInterpolate.h"
#include "cTrack.h"

#pragma pack(pop)